// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer_DatabaseFirst.Models;

[Keyless]
public partial class CustomerOrdersView
{
    public int CustomerId { get; set; }

    [Required]
    [StringLength(100)]
    public string CustomerName { get; set; }

    public int OrderId { get; set; }

    public int? Rating { get; set; }

    public string Review { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Date { get; set; }
}