// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DataAccessLayer_DatabaseFirst.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DataAccessLayer_DatabaseFirst.Models
{
    public partial interface IApplicationDbContextProcedures
    {
        Task<List<sp_GetCustomerOrdersResult>> sp_GetCustomerOrdersAsync(int? CustomerId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_GetProductSalesResult>> sp_GetProductSalesAsync(int? ProductId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
