// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer_DatabaseFirst.Models;

[PrimaryKey("OrderId", "ProductId")]
[Table("OrderProduct")]
public partial class OrderProduct
{
    [Key]
    public int OrderId { get; set; }

    [Key]
    public int ProductId { get; set; }

    public int Amount { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("OrderProducts")]
    public virtual Order Order { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("OrderProducts")]
    public virtual Product Product { get; set; }
}