// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer_DatabaseFirst.Models
{
    public partial class sp_GetProductSalesResult
    {
        public string ProductName { get; set; }
        public int? TotalAmountSold { get; set; }
        public int? NumberOfOrders { get; set; }
    }
}
