// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer_DatabaseFirst.Models
{
    public partial class sp_GetCustomerOrdersResult
    {
        public int OrderId { get; set; }
        public DateTime Date { get; set; }
        public int? Rating { get; set; }
        public string Review { get; set; }
    }
}
